//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.06 at 02:39:16 PM IST 
//


package com.arris.sfdc.pojo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StandardPriceBookOutput" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PriceBookEntryOutput" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="HNMPriceBookEntryOutput" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "standardPriceBookOutput",
    "priceBookEntryOutput",
    "hnmPriceBookEntryOutput"
})
@XmlRootElement(name = "QueryPriceBookOutput")
public class QueryPriceBookOutput {

    @XmlElement(name = "StandardPriceBookOutput", required = false)
    protected QueryPriceBookOutput.StandardPriceBookOutput standardPriceBookOutput;
    @XmlElement(name = "PriceBookEntryOutput", required = false)
    protected QueryPriceBookOutput.PriceBookEntryOutput priceBookEntryOutput;
    @XmlElement(name = "HNMPriceBookEntryOutput", required = false)
    protected QueryPriceBookOutput.HNMPriceBookEntryOutput hnmPriceBookEntryOutput;

    /**
     * Gets the value of the standardPriceBookOutput property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link QueryPriceBookOutput.StandardPriceBookOutput }{@code >}
     *     
     */
    public QueryPriceBookOutput.StandardPriceBookOutput getStandardPriceBookOutput() {
        return standardPriceBookOutput;
    }

    /**
     * Sets the value of the standardPriceBookOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link QueryPriceBookOutput.StandardPriceBookOutput }{@code >}
     *     
     */
    public void setStandardPriceBookOutput(QueryPriceBookOutput.StandardPriceBookOutput value) {
        this.standardPriceBookOutput = value;
    }

    /**
     * Gets the value of the priceBookEntryOutput property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link QueryPriceBookOutput.PriceBookEntryOutput }{@code >}
     *     
     */
    public QueryPriceBookOutput.PriceBookEntryOutput getPriceBookEntryOutput() {
        return priceBookEntryOutput;
    }

    /**
     * Sets the value of the priceBookEntryOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link QueryPriceBookOutput.PriceBookEntryOutput }{@code >}
     *     
     */
    public void setPriceBookEntryOutput(QueryPriceBookOutput.PriceBookEntryOutput value) {
        this.priceBookEntryOutput = value;
    }

    /**
     * Gets the value of the hnmPriceBookEntryOutput property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link QueryPriceBookOutput.HNMPriceBookEntryOutput }{@code >}
     *     
     */
    public QueryPriceBookOutput.HNMPriceBookEntryOutput getHNMPriceBookEntryOutput() {
        return hnmPriceBookEntryOutput;
    }

    /**
     * Sets the value of the hnmPriceBookEntryOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link QueryPriceBookOutput.HNMPriceBookEntryOutput }{@code >}
     *     
     */
    public void setHNMPriceBookEntryOutput(QueryPriceBookOutput.HNMPriceBookEntryOutput value) {
        this.hnmPriceBookEntryOutput = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id"
    })
    public static class HNMPriceBookEntryOutput {

        @XmlElement(name = "Id", required = false)
        protected String id;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id"
    })
    public static class PriceBookEntryOutput {

        @XmlElement(name = "Id", required = false)
        protected String id;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id"
    })
    public static class StandardPriceBookOutput {

        @XmlElement(name = "Id", required = false)
        protected String id;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

    }

}
