//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.06 at 06:33:58 PM IST 
//


package com.arris.sfdc.pojo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Operation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UpdateStandardPriceBookInput" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="IsActive" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="UnitPrice" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="CreatePriceBookEntryInput" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CurrencyIsoCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="IsActive" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Pricebook2Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Product2Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="UnitPrice" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="UpdateHNMPriceBookInput" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="UnitPrice" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "operation",
    "updateStandardPriceBookInput",
    "createPriceBookEntryInput",
    "updateHNMPriceBookInput"
})
@XmlRootElement(name = "PriceBookInput")
public class PriceBookInput {

    @XmlElement(name = "Operation")
    protected String operation;
    @XmlElement(name = "UpdateStandardPriceBookInput", required = false)
    protected PriceBookInput.UpdateStandardPriceBookInput updateStandardPriceBookInput;
    @XmlElement(name = "CreatePriceBookEntryInput", required = false)
    protected PriceBookInput.CreatePriceBookEntryInput createPriceBookEntryInput;
    @XmlElement(name = "UpdateHNMPriceBookInput", required = false)
    protected PriceBookInput.UpdateHNMPriceBookInput updateHNMPriceBookInput;

    /**
     * Gets the value of the operation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperation() {
        return operation;
    }

    /**
     * Sets the value of the operation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperation(String value) {
        this.operation = value;
    }

    /**
     * Gets the value of the updateStandardPriceBookInput property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PriceBookInput.UpdateStandardPriceBookInput }{@code >}
     *     
     */
    public PriceBookInput.UpdateStandardPriceBookInput getUpdateStandardPriceBookInput() {
        return updateStandardPriceBookInput;
    }

    /**
     * Sets the value of the updateStandardPriceBookInput property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PriceBookInput.UpdateStandardPriceBookInput }{@code >}
     *     
     */
    public void setUpdateStandardPriceBookInput(PriceBookInput.UpdateStandardPriceBookInput value) {
        this.updateStandardPriceBookInput = value;
    }

    /**
     * Gets the value of the createPriceBookEntryInput property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PriceBookInput.CreatePriceBookEntryInput }{@code >}
     *     
     */
    public PriceBookInput.CreatePriceBookEntryInput getCreatePriceBookEntryInput() {
        return createPriceBookEntryInput;
    }

    /**
     * Sets the value of the createPriceBookEntryInput property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PriceBookInput.CreatePriceBookEntryInput }{@code >}
     *     
     */
    public void setCreatePriceBookEntryInput(PriceBookInput.CreatePriceBookEntryInput value) {
        this.createPriceBookEntryInput = value;
    }

    /**
     * Gets the value of the updateHNMPriceBookInput property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PriceBookInput.UpdateHNMPriceBookInput }{@code >}
     *     
     */
    public PriceBookInput.UpdateHNMPriceBookInput getUpdateHNMPriceBookInput() {
        return updateHNMPriceBookInput;
    }

    /**
     * Sets the value of the updateHNMPriceBookInput property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PriceBookInput.UpdateHNMPriceBookInput }{@code >}
     *     
     */
    public void setUpdateHNMPriceBookInput(PriceBookInput.UpdateHNMPriceBookInput value) {
        this.updateHNMPriceBookInput = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CurrencyIsoCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="IsActive" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Pricebook2Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Product2Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="UnitPrice" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "currencyIsoCode",
        "isActive",
        "pricebook2Id",
        "product2Id",
        "unitPrice"
    })
    public static class CreatePriceBookEntryInput {

        @XmlElement(name = "CurrencyIsoCode", required = false)
        protected String currencyIsoCode;
        @XmlElement(name = "IsActive", required = false)
        protected String isActive;
        @XmlElement(name = "Pricebook2Id", required = false)
        protected String pricebook2Id;
        @XmlElement(name = "Product2Id", required = false)
        protected String product2Id;
        @XmlElement(name = "UnitPrice", required = false)
        protected String unitPrice;

        /**
         * Gets the value of the currencyIsoCode property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getCurrencyIsoCode() {
            return currencyIsoCode;
        }

        /**
         * Sets the value of the currencyIsoCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setCurrencyIsoCode(String value) {
            this.currencyIsoCode = value;
        }

        /**
         * Gets the value of the isActive property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getIsActive() {
            return isActive;
        }

        /**
         * Sets the value of the isActive property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setIsActive(String value) {
            this.isActive = value;
        }

        /**
         * Gets the value of the pricebook2Id property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getPricebook2Id() {
            return pricebook2Id;
        }

        /**
         * Sets the value of the pricebook2Id property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setPricebook2Id(String value) {
            this.pricebook2Id = value;
        }

        /**
         * Gets the value of the product2Id property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getProduct2Id() {
            return product2Id;
        }

        /**
         * Sets the value of the product2Id property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setProduct2Id(String value) {
            this.product2Id = value;
        }

        /**
         * Gets the value of the unitPrice property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getUnitPrice() {
            return unitPrice;
        }

        /**
         * Sets the value of the unitPrice property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setUnitPrice(String value) {
            this.unitPrice = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="UnitPrice" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "unitPrice"
    })
    public static class UpdateHNMPriceBookInput {

        @XmlElement(name = "Id", required = false)
        protected String id;
        @XmlElement(name = "UnitPrice", required = false)
        protected String unitPrice;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the unitPrice property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getUnitPrice() {
            return unitPrice;
        }

        /**
         * Sets the value of the unitPrice property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setUnitPrice(String value) {
            this.unitPrice = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="IsActive" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="UnitPrice" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "isActive",
        "unitPrice"
    })
    public static class UpdateStandardPriceBookInput {

        @XmlElement(name = "Id", required = false)
        protected String id;
        @XmlElement(name = "IsActive", required = false)
        protected String isActive;
        @XmlElement(name = "UnitPrice", required = false)
        protected String unitPrice;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the isActive property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getIsActive() {
            return isActive;
        }

        /**
         * Sets the value of the isActive property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setIsActive(String value) {
            this.isActive = value;
        }

        /**
         * Gets the value of the unitPrice property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getUnitPrice() {
            return unitPrice;
        }

        /**
         * Sets the value of the unitPrice property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setUnitPrice(String value) {
            this.unitPrice = value;
        }

    }

}
