//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.15 at 12:53:06 PM IST 
//


package com.arris.sfdc.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RecordTypeId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Customer_Number_HnM__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Customer_Number__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Region__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Status__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Active__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Source_System__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "type",
    "recordTypeId",
    "customerNumberHnMC",
    "customerNumberC",
    "regionC",
    "statusC",
    "activeC",
    "sourceSystemC"
})
@XmlRootElement(name = "InputElement")
public class InputElement {

    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "Type")
    protected String type;
    @XmlElement(name = "RecordTypeId")
    protected String recordTypeId;
    @XmlElement(name = "Customer_Number_HnM__c")
    protected String customerNumberHnMC;
    @XmlElement(name = "Customer_Number__c")
    protected String customerNumberC;
    @XmlElement(name = "Region__c")
    protected String regionC;
    @XmlElement(name = "Status__c")
    protected String statusC;
    @XmlElement(name = "Active__c")
    protected String activeC;
    @XmlElement(name = "Source_System__c")
    protected String sourceSystemC;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the recordTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordTypeId() {
        return recordTypeId;
    }

    /**
     * Sets the value of the recordTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordTypeId(String value) {
        this.recordTypeId = value;
    }

    /**
     * Gets the value of the customerNumberHnMC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerNumberHnMC() {
        return customerNumberHnMC;
    }

    /**
     * Sets the value of the customerNumberHnMC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerNumberHnMC(String value) {
        this.customerNumberHnMC = value;
    }

    /**
     * Gets the value of the customerNumberC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerNumberC() {
        return customerNumberC;
    }

    /**
     * Sets the value of the customerNumberC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerNumberC(String value) {
        this.customerNumberC = value;
    }

    /**
     * Gets the value of the regionC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegionC() {
        return regionC;
    }

    /**
     * Sets the value of the regionC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegionC(String value) {
        this.regionC = value;
    }

    /**
     * Gets the value of the statusC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusC() {
        return statusC;
    }

    /**
     * Sets the value of the statusC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusC(String value) {
        this.statusC = value;
    }

    /**
     * Gets the value of the activeC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActiveC() {
        return activeC;
    }

    /**
     * Sets the value of the activeC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActiveC(String value) {
        this.activeC = value;
    }

    /**
     * Gets the value of the sourceSystemC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceSystemC() {
        return sourceSystemC;
    }

    /**
     * Sets the value of the sourceSystemC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceSystemC(String value) {
        this.sourceSystemC = value;
    }

	@Override
	public String toString() {
		return "InputElement [name=" + name + ", type=" + type
				+ ", recordTypeId=" + recordTypeId + ", customerNumberHnMC="
				+ customerNumberHnMC + ", customerNumberC=" + customerNumberC
				+ ", regionC=" + regionC + ", statusC=" + statusC
				+ ", activeC=" + activeC + ", sourceSystemC=" + sourceSystemC
				+ "]";
	}
}
