//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.20 at 05:54:47 PM IST 
//


package com.arris.sfdc.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Operation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="QueryPONumberInput" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Interface_Status__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="QueryPODetailsInput" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PO_Number__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="UpdateInterfaceStatusInput" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Interface_Date_Time__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Interface_Error_Message__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Interface_Status__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="PO_Number__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "operation",
    "queryPONumberInput",
    "queryPODetailsInput",
    "updateInterfaceStatusInput"
})
@XmlRootElement(name = "OrderImportInput")
public class OrderImportInput {

    @XmlElement(name = "Operation")
    protected String operation;
    @XmlElement(name = "QueryPONumberInput")
    protected OrderImportInput.QueryPONumberInput queryPONumberInput;
    @XmlElement(name = "QueryPODetailsInput")
    protected OrderImportInput.QueryPODetailsInput queryPODetailsInput;
    @XmlElement(name = "UpdateInterfaceStatusInput")
    protected OrderImportInput.UpdateInterfaceStatusInput updateInterfaceStatusInput;

    /**
     * Gets the value of the operation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperation() {
        return operation;
    }

    /**
     * Sets the value of the operation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperation(String value) {
        this.operation = value;
    }

    /**
     * Gets the value of the queryPONumberInput property.
     * 
     * @return
     *     possible object is
     *     {@link OrderImportInput.QueryPONumberInput }
     *     
     */
    public OrderImportInput.QueryPONumberInput getQueryPONumberInput() {
        return queryPONumberInput;
    }

    /**
     * Sets the value of the queryPONumberInput property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderImportInput.QueryPONumberInput }
     *     
     */
    public void setQueryPONumberInput(OrderImportInput.QueryPONumberInput value) {
        this.queryPONumberInput = value;
    }

    /**
     * Gets the value of the queryPODetailsInput property.
     * 
     * @return
     *     possible object is
     *     {@link OrderImportInput.QueryPODetailsInput }
     *     
     */
    public OrderImportInput.QueryPODetailsInput getQueryPODetailsInput() {
        return queryPODetailsInput;
    }

    /**
     * Sets the value of the queryPODetailsInput property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderImportInput.QueryPODetailsInput }
     *     
     */
    public void setQueryPODetailsInput(OrderImportInput.QueryPODetailsInput value) {
        this.queryPODetailsInput = value;
    }

    /**
     * Gets the value of the updateInterfaceStatusInput property.
     * 
     * @return
     *     possible object is
     *     {@link OrderImportInput.UpdateInterfaceStatusInput }
     *     
     */
    public OrderImportInput.UpdateInterfaceStatusInput getUpdateInterfaceStatusInput() {
        return updateInterfaceStatusInput;
    }

    /**
     * Sets the value of the updateInterfaceStatusInput property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderImportInput.UpdateInterfaceStatusInput }
     *     
     */
    public void setUpdateInterfaceStatusInput(OrderImportInput.UpdateInterfaceStatusInput value) {
        this.updateInterfaceStatusInput = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PO_Number__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "poNumberC"
    })
    public static class QueryPODetailsInput {

        @XmlElement(name = "PO_Number__c")
        protected String poNumberC;

        /**
         * Gets the value of the poNumberC property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPONumberC() {
            return poNumberC;
        }

        /**
         * Sets the value of the poNumberC property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPONumberC(String value) {
            this.poNumberC = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Interface_Status__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "interfaceStatusC"
    })
    public static class QueryPONumberInput {

        @XmlElement(name = "Interface_Status__c")
        protected String interfaceStatusC;

        /**
         * Gets the value of the interfaceStatusC property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInterfaceStatusC() {
            return interfaceStatusC;
        }

        /**
         * Sets the value of the interfaceStatusC property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInterfaceStatusC(String value) {
            this.interfaceStatusC = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Interface_Date_Time__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Interface_Error_Message__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Interface_Status__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="PO_Number__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "interfaceDateTimeC",
        "interfaceErrorMessageC",
        "interfaceStatusC",
        "poNumberC"
    })
    public static class UpdateInterfaceStatusInput {

        @XmlElement(name = "Id")
        protected String id;
        @XmlElement(name = "Interface_Date_Time__c")
        protected String interfaceDateTimeC;
        @XmlElement(name = "Interface_Error_Message__c")
        protected String interfaceErrorMessageC;
        @XmlElement(name = "Interface_Status__c")
        protected String interfaceStatusC;
        @XmlElement(name = "PO_Number__c")
        protected String poNumberC;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the interfaceDateTimeC property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInterfaceDateTimeC() {
            return interfaceDateTimeC;
        }

        /**
         * Sets the value of the interfaceDateTimeC property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInterfaceDateTimeC(String value) {
            this.interfaceDateTimeC = value;
        }

        /**
         * Gets the value of the interfaceErrorMessageC property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInterfaceErrorMessageC() {
            return interfaceErrorMessageC;
        }

        /**
         * Sets the value of the interfaceErrorMessageC property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInterfaceErrorMessageC(String value) {
            this.interfaceErrorMessageC = value;
        }

        /**
         * Gets the value of the interfaceStatusC property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInterfaceStatusC() {
            return interfaceStatusC;
        }

        /**
         * Sets the value of the interfaceStatusC property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInterfaceStatusC(String value) {
            this.interfaceStatusC = value;
        }

        /**
         * Gets the value of the poNumberC property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPONumberC() {
            return poNumberC;
        }

        /**
         * Sets the value of the poNumberC property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPONumberC(String value) {
            this.poNumberC = value;
        }

    }

}
