//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.20 at 05:54:47 PM IST 
//


package com.arris.sfdc.pojo;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="QueryPONumberOutput" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PO_Number__c" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="QueryPODetailsOutput" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ASN_Email__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Account_Number__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Attention_To__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Business_Group__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Cancelled_Quantity__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="CurrencyIsoCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Customer_Item_Number__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Customer_Number__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Department__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="External_Line_Ref__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="External_Order_Ref__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="FOB__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Freight_Terms__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Fulfillment_Service_Level__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Header_ATTRIBUTE1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Header_ATTRIBUTE2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Header_ATTRIBUTE3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Header_Bill_To_Use_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Header_CRRD__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Header_Notes__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Header_Ship_To_Use_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Item_Number__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Line_ATTRIBUTE1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Line_ATTRIBUTE2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Line_ATTRIBUTE4" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Line_Bill_To_Use_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Line_CRSD__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Line_Notes__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Line_Ship_To_Use_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Line_Shipment_Method__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Line_Type__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="OU_ID__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="OU_Name__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Order_Date__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Order_Type__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Ordered_Quantity__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="PO_Number__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Packing_Instructions__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Payment_Terms__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Po_Line_Number__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Price_Date__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Pricelist_Name__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Primary_SalesRep_Name__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Return_Reason_Code__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="SOA__Email__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Sales_Program__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Ship_Partial_Flag__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Ship_To_Loc_Code__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Shipping_Amount__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Shipping_Instructions__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Tax_State__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="UOM__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Unit_Price__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="UpdateInterfaceStatusOutput" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="errors" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="success" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "queryPONumberOutput",
    "queryPODetailsOutput",
    "updateInterfaceStatusOutput"
})
@XmlRootElement(name = "OrderImportOutput")
public class OrderImportOutput {

    @XmlElement(name = "QueryPONumberOutput")
    protected OrderImportOutput.QueryPONumberOutput queryPONumberOutput;
    @XmlElement(name = "QueryPODetailsOutput")
    protected List<OrderImportOutput.QueryPODetailsOutput> queryPODetailsOutput;
    @XmlElement(name = "UpdateInterfaceStatusOutput")
    protected OrderImportOutput.UpdateInterfaceStatusOutput updateInterfaceStatusOutput;

    /**
     * Gets the value of the queryPONumberOutput property.
     * 
     * @return
     *     possible object is
     *     {@link OrderImportOutput.QueryPONumberOutput }
     *     
     */
    public OrderImportOutput.QueryPONumberOutput getQueryPONumberOutput() {
        return queryPONumberOutput;
    }

    /**
     * Sets the value of the queryPONumberOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderImportOutput.QueryPONumberOutput }
     *     
     */
    public void setQueryPONumberOutput(OrderImportOutput.QueryPONumberOutput value) {
        this.queryPONumberOutput = value;
    }

    /**
     * Gets the value of the queryPODetailsOutput property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the queryPODetailsOutput property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQueryPODetailsOutput().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrderImportOutput.QueryPODetailsOutput }
     * 
     * 
     */
    public List<OrderImportOutput.QueryPODetailsOutput> getQueryPODetailsOutput() {
        if (queryPODetailsOutput == null) {
            queryPODetailsOutput = new ArrayList<OrderImportOutput.QueryPODetailsOutput>();
        }
        return this.queryPODetailsOutput;
    }

    /**
     * Gets the value of the updateInterfaceStatusOutput property.
     * 
     * @return
     *     possible object is
     *     {@link OrderImportOutput.UpdateInterfaceStatusOutput }
     *     
     */
    public OrderImportOutput.UpdateInterfaceStatusOutput getUpdateInterfaceStatusOutput() {
        return updateInterfaceStatusOutput;
    }

    /**
     * Sets the value of the updateInterfaceStatusOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderImportOutput.UpdateInterfaceStatusOutput }
     *     
     */
    public void setUpdateInterfaceStatusOutput(OrderImportOutput.UpdateInterfaceStatusOutput value) {
        this.updateInterfaceStatusOutput = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ASN_Email__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Account_Number__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Attention_To__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Business_Group__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Cancelled_Quantity__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="CurrencyIsoCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Customer_Item_Number__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Customer_Number__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Department__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="External_Line_Ref__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="External_Order_Ref__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="FOB__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Freight_Terms__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Fulfillment_Service_Level__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Header_ATTRIBUTE1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Header_ATTRIBUTE2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Header_ATTRIBUTE3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Header_Bill_To_Use_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Header_CRRD__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Header_Notes__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Header_Ship_To_Use_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Item_Number__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Line_ATTRIBUTE1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Line_ATTRIBUTE2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Line_ATTRIBUTE4" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Line_Bill_To_Use_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Line_CRSD__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Line_Notes__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Line_Ship_To_Use_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Line_Shipment_Method__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Line_Type__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="OU_ID__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="OU_Name__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Order_Date__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Order_Type__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Ordered_Quantity__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="PO_Number__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Packing_Instructions__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Payment_Terms__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Po_Line_Number__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Price_Date__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Pricelist_Name__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Primary_SalesRep_Name__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Return_Reason_Code__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="SOA__Email__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Sales_Program__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Ship_Partial_Flag__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Ship_To_Loc_Code__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Shipping_Amount__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Shipping_Instructions__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Tax_State__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="UOM__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Unit_Price__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "asnEmailC",
        "accountNumberC",
        "attentionToC",
        "businessGroupC",
        "cancelledQuantityC",
        "currencyIsoCode",
        "customerItemNumberC",
        "customerNumberC",
        "departmentC",
        "externalLineRefC",
        "externalOrderRefC",
        "fobc",
        "freightTermsC",
        "fulfillmentServiceLevelC",
        "headerATTRIBUTE1",
        "headerATTRIBUTE2",
        "headerATTRIBUTE3",
        "headerBillToUseID",
        "headerCRRDC",
        "headerNotesC",
        "headerShipToUseID",
        "id",
        "itemNumberC",
        "lineATTRIBUTE1",
        "lineATTRIBUTE2",
        "lineATTRIBUTE4",
        "lineBillToUseID",
        "lineCRSDC",
        "lineNotesC",
        "lineShipToUseID",
        "lineShipmentMethodC",
        "lineTypeC",
        "ouidc",
        "ouNameC",
        "orderDateC",
        "orderTypeC",
        "orderedQuantityC",
        "poNumberC",
        "packingInstructionsC",
        "paymentTermsC",
        "poLineNumberC",
        "priceDateC",
        "pricelistNameC",
        "primarySalesRepNameC",
        "returnReasonCodeC",
        "soaEmailC",
        "salesProgramC",
        "shipPartialFlagC",
        "shipToLocCodeC",
        "shippingAmountC",
        "shippingInstructionsC",
        "taxStateC",
        "uomc",
        "unitPriceC"
    })
    public static class QueryPODetailsOutput {

        @XmlElement(name = "ASN_Email__c", required = false)
        protected String asnEmailC;
        @XmlElement(name = "Account_Number__c", required = false)
        protected String accountNumberC;
        @XmlElement(name = "Attention_To__c", required = false)
        protected String attentionToC;
        @XmlElement(name = "Business_Group__c", required = false)
        protected String businessGroupC;
        @XmlElement(name = "Cancelled_Quantity__c", required = false)
        protected String cancelledQuantityC;
        @XmlElement(name = "CurrencyIsoCode", required = false)
        protected String currencyIsoCode;
        @XmlElement(name = "Customer_Item_Number__c", required = false)
        protected String customerItemNumberC;
        @XmlElement(name = "Customer_Number__c", required = false)
        protected String customerNumberC;
        @XmlElement(name = "Department__c", required = false)
        protected String departmentC;
        @XmlElement(name = "External_Line_Ref__c", required = false)
        protected String externalLineRefC;
        @XmlElement(name = "External_Order_Ref__c", required = false)
        protected String externalOrderRefC;
        @XmlElement(name = "FOB__c", required = false)
        protected String fobc;
        @XmlElement(name = "Freight_Terms__c", required = false)
        protected String freightTermsC;
        @XmlElement(name = "Fulfillment_Service_Level__c", required = false)
        protected String fulfillmentServiceLevelC;
        @XmlElement(name = "Header_ATTRIBUTE1", required = false)
        protected String headerATTRIBUTE1;
        @XmlElement(name = "Header_ATTRIBUTE2", required = false)
        protected String headerATTRIBUTE2;
        @XmlElement(name = "Header_ATTRIBUTE3", required = false)
        protected String headerATTRIBUTE3;
        @XmlElement(name = "Header_Bill_To_Use_ID", required = false)
        protected String headerBillToUseID;
        @XmlElement(name = "Header_CRRD__c", required = false)
        protected String headerCRRDC;
        @XmlElement(name = "Header_Notes__c", required = false)
        protected String headerNotesC;
        @XmlElement(name = "Header_Ship_To_Use_ID", required = false)
        protected String headerShipToUseID;
        @XmlElement(name = "Id", required = false)
        protected String id;
        @XmlElement(name = "Item_Number__c", required = false)
        protected String itemNumberC;
        @XmlElement(name = "Line_ATTRIBUTE1", required = false)
        protected String lineATTRIBUTE1;
        @XmlElement(name = "Line_ATTRIBUTE2", required = false)
        protected String lineATTRIBUTE2;
        @XmlElement(name = "Line_ATTRIBUTE4", required = false)
        protected String lineATTRIBUTE4;
        @XmlElement(name = "Line_Bill_To_Use_ID", required = false)
        protected String lineBillToUseID;
        @XmlElement(name = "Line_CRSD__c", required = false)
        protected String lineCRSDC;
        @XmlElement(name = "Line_Notes__c", required = false)
        protected String lineNotesC;
        @XmlElement(name = "Line_Ship_To_Use_ID", required = false)
        protected String lineShipToUseID;
        @XmlElement(name = "Line_Shipment_Method__c", required = false)
        protected String lineShipmentMethodC;
        @XmlElement(name = "Line_Type__c", required = false)
        protected String lineTypeC;
        @XmlElement(name = "OU_ID__c", required = false)
        protected String ouidc;
        @XmlElement(name = "OU_Name__c", required = false)
        protected String ouNameC;
        @XmlElement(name = "Order_Date__c", required = false)
        protected String orderDateC;
        @XmlElement(name = "Order_Type__c", required = false)
        protected String orderTypeC;
        @XmlElement(name = "Ordered_Quantity__c", required = false)
        protected String orderedQuantityC;
        @XmlElement(name = "PO_Number__c", required = false)
        protected String poNumberC;
        @XmlElement(name = "Packing_Instructions__c", required = false)
        protected String packingInstructionsC;
        @XmlElement(name = "Payment_Terms__c", required = false)
        protected String paymentTermsC;
        @XmlElement(name = "Po_Line_Number__c", required = false)
        protected String poLineNumberC;
        @XmlElement(name = "Price_Date__c", required = false)
        protected String priceDateC;
        @XmlElement(name = "Pricelist_Name__c", required = false)
        protected String pricelistNameC;
        @XmlElement(name = "Primary_SalesRep_Name__c", required = false)
        protected String primarySalesRepNameC;
        @XmlElement(name = "Return_Reason_Code__c", required = false)
        protected String returnReasonCodeC;
        @XmlElement(name = "SOA__Email__c", required = false)
        protected String soaEmailC;
        @XmlElement(name = "Sales_Program__c", required = false)
        protected String salesProgramC;
        @XmlElement(name = "Ship_Partial_Flag__c", required = false)
        protected String shipPartialFlagC;
        @XmlElement(name = "Ship_To_Loc_Code__c", required = false)
        protected String shipToLocCodeC;
        @XmlElement(name = "Shipping_Amount__c", required = false)
        protected String shippingAmountC;
        @XmlElement(name = "Shipping_Instructions__c", required = false)
        protected String shippingInstructionsC;
        @XmlElement(name = "Tax_State__c", required = false)
        protected String taxStateC;
        @XmlElement(name = "UOM__c", required = false)
        protected String uomc;
        @XmlElement(name = "Unit_Price__c", required = false)
        protected String unitPriceC;

        /**
         * Gets the value of the asnEmailC property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getASNEmailC() {
            return asnEmailC;
        }

        /**
         * Sets the value of the asnEmailC property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setASNEmailC(String value) {
            this.asnEmailC = value;
        }

        /**
         * Gets the value of the accountNumberC property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getAccountNumberC() {
            return accountNumberC;
        }

        /**
         * Sets the value of the accountNumberC property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setAccountNumberC(String value) {
            this.accountNumberC = value;
        }

        /**
         * Gets the value of the attentionToC property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getAttentionToC() {
            return attentionToC;
        }

        /**
         * Sets the value of the attentionToC property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setAttentionToC(String value) {
            this.attentionToC = value;
        }

        /**
         * Gets the value of the businessGroupC property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getBusinessGroupC() {
            return businessGroupC;
        }

        /**
         * Sets the value of the businessGroupC property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setBusinessGroupC(String value) {
            this.businessGroupC = value;
        }

        /**
         * Gets the value of the cancelledQuantityC property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getCancelledQuantityC() {
            return cancelledQuantityC;
        }

        /**
         * Sets the value of the cancelledQuantityC property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setCancelledQuantityC(String value) {
            this.cancelledQuantityC = value;
        }

        /**
         * Gets the value of the currencyIsoCode property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getCurrencyIsoCode() {
            return currencyIsoCode;
        }

        /**
         * Sets the value of the currencyIsoCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setCurrencyIsoCode(String value) {
            this.currencyIsoCode = value;
        }

        /**
         * Gets the value of the customerItemNumberC property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getCustomerItemNumberC() {
            return customerItemNumberC;
        }

        /**
         * Sets the value of the customerItemNumberC property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setCustomerItemNumberC(String value) {
            this.customerItemNumberC = value;
        }

        /**
         * Gets the value of the customerNumberC property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getCustomerNumberC() {
            return customerNumberC;
        }

        /**
         * Sets the value of the customerNumberC property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setCustomerNumberC(String value) {
            this.customerNumberC = value;
        }

        /**
         * Gets the value of the departmentC property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getDepartmentC() {
            return departmentC;
        }

        /**
         * Sets the value of the departmentC property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setDepartmentC(String value) {
            this.departmentC = value;
        }

        /**
         * Gets the value of the externalLineRefC property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getExternalLineRefC() {
            return externalLineRefC;
        }

        /**
         * Sets the value of the externalLineRefC property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setExternalLineRefC(String value) {
            this.externalLineRefC = value;
        }

        /**
         * Gets the value of the externalOrderRefC property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getExternalOrderRefC() {
            return externalOrderRefC;
        }

        /**
         * Sets the value of the externalOrderRefC property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setExternalOrderRefC(String value) {
            this.externalOrderRefC = value;
        }

        /**
         * Gets the value of the fobc property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getFOBC() {
            return fobc;
        }

        /**
         * Sets the value of the fobc property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setFOBC(String value) {
            this.fobc = value;
        }

        /**
         * Gets the value of the freightTermsC property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getFreightTermsC() {
            return freightTermsC;
        }

        /**
         * Sets the value of the freightTermsC property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setFreightTermsC(String value) {
            this.freightTermsC = value;
        }

        /**
         * Gets the value of the fulfillmentServiceLevelC property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getFulfillmentServiceLevelC() {
            return fulfillmentServiceLevelC;
        }

        /**
         * Sets the value of the fulfillmentServiceLevelC property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setFulfillmentServiceLevelC(String value) {
            this.fulfillmentServiceLevelC = value;
        }

        /**
         * Gets the value of the headerATTRIBUTE1 property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getHeaderATTRIBUTE1() {
            return headerATTRIBUTE1;
        }

        /**
         * Sets the value of the headerATTRIBUTE1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setHeaderATTRIBUTE1(String value) {
            this.headerATTRIBUTE1 = value;
        }

        /**
         * Gets the value of the headerATTRIBUTE2 property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getHeaderATTRIBUTE2() {
            return headerATTRIBUTE2;
        }

        /**
         * Sets the value of the headerATTRIBUTE2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setHeaderATTRIBUTE2(String value) {
            this.headerATTRIBUTE2 = value;
        }

        /**
         * Gets the value of the headerATTRIBUTE3 property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getHeaderATTRIBUTE3() {
            return headerATTRIBUTE3;
        }

        /**
         * Sets the value of the headerATTRIBUTE3 property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setHeaderATTRIBUTE3(String value) {
            this.headerATTRIBUTE3 = value;
        }

        /**
         * Gets the value of the headerBillToUseID property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getHeaderBillToUseID() {
            return headerBillToUseID;
        }

        /**
         * Sets the value of the headerBillToUseID property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setHeaderBillToUseID(String value) {
            this.headerBillToUseID = value;
        }

        /**
         * Gets the value of the headerCRRDC property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getHeaderCRRDC() {
            return headerCRRDC;
        }

        /**
         * Sets the value of the headerCRRDC property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setHeaderCRRDC(String value) {
            this.headerCRRDC = value;
        }

        /**
         * Gets the value of the headerNotesC property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getHeaderNotesC() {
            return headerNotesC;
        }

        /**
         * Sets the value of the headerNotesC property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setHeaderNotesC(String value) {
            this.headerNotesC = value;
        }

        /**
         * Gets the value of the headerShipToUseID property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getHeaderShipToUseID() {
            return headerShipToUseID;
        }

        /**
         * Sets the value of the headerShipToUseID property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setHeaderShipToUseID(String value) {
            this.headerShipToUseID = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the itemNumberC property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getItemNumberC() {
            return itemNumberC;
        }

        /**
         * Sets the value of the itemNumberC property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setItemNumberC(String value) {
            this.itemNumberC = value;
        }

        /**
         * Gets the value of the lineATTRIBUTE1 property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getLineATTRIBUTE1() {
            return lineATTRIBUTE1;
        }

        /**
         * Sets the value of the lineATTRIBUTE1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setLineATTRIBUTE1(String value) {
            this.lineATTRIBUTE1 = value;
        }

        /**
         * Gets the value of the lineATTRIBUTE2 property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getLineATTRIBUTE2() {
            return lineATTRIBUTE2;
        }

        /**
         * Sets the value of the lineATTRIBUTE2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setLineATTRIBUTE2(String value) {
            this.lineATTRIBUTE2 = value;
        }

        /**
         * Gets the value of the lineATTRIBUTE4 property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getLineATTRIBUTE4() {
            return lineATTRIBUTE4;
        }

        /**
         * Sets the value of the lineATTRIBUTE4 property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setLineATTRIBUTE4(String value) {
            this.lineATTRIBUTE4 = value;
        }

        /**
         * Gets the value of the lineBillToUseID property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getLineBillToUseID() {
            return lineBillToUseID;
        }

        /**
         * Sets the value of the lineBillToUseID property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setLineBillToUseID(String value) {
            this.lineBillToUseID = value;
        }

        /**
         * Gets the value of the lineCRSDC property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getLineCRSDC() {
            return lineCRSDC;
        }

        /**
         * Sets the value of the lineCRSDC property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setLineCRSDC(String value) {
            this.lineCRSDC = value;
        }

        /**
         * Gets the value of the lineNotesC property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getLineNotesC() {
            return lineNotesC;
        }

        /**
         * Sets the value of the lineNotesC property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setLineNotesC(String value) {
            this.lineNotesC = value;
        }

        /**
         * Gets the value of the lineShipToUseID property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getLineShipToUseID() {
            return lineShipToUseID;
        }

        /**
         * Sets the value of the lineShipToUseID property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setLineShipToUseID(String value) {
            this.lineShipToUseID = value;
        }

        /**
         * Gets the value of the lineShipmentMethodC property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getLineShipmentMethodC() {
            return lineShipmentMethodC;
        }

        /**
         * Sets the value of the lineShipmentMethodC property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setLineShipmentMethodC(String value) {
            this.lineShipmentMethodC = value;
        }

        /**
         * Gets the value of the lineTypeC property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getLineTypeC() {
            return lineTypeC;
        }

        /**
         * Sets the value of the lineTypeC property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setLineTypeC(String value) {
            this.lineTypeC = value;
        }

        /**
         * Gets the value of the ouidc property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getOUIDC() {
            return ouidc;
        }

        /**
         * Sets the value of the ouidc property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setOUIDC(String value) {
            this.ouidc = value;
        }

        /**
         * Gets the value of the ouNameC property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getOUNameC() {
            return ouNameC;
        }

        /**
         * Sets the value of the ouNameC property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setOUNameC(String value) {
            this.ouNameC = value;
        }

        /**
         * Gets the value of the orderDateC property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getOrderDateC() {
            return orderDateC;
        }

        /**
         * Sets the value of the orderDateC property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setOrderDateC(String value) {
            this.orderDateC = value;
        }

        /**
         * Gets the value of the orderTypeC property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getOrderTypeC() {
            return orderTypeC;
        }

        /**
         * Sets the value of the orderTypeC property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setOrderTypeC(String value) {
            this.orderTypeC = value;
        }

        /**
         * Gets the value of the orderedQuantityC property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getOrderedQuantityC() {
            return orderedQuantityC;
        }

        /**
         * Sets the value of the orderedQuantityC property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setOrderedQuantityC(String value) {
            this.orderedQuantityC = value;
        }

        /**
         * Gets the value of the poNumberC property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getPONumberC() {
            return poNumberC;
        }

        /**
         * Sets the value of the poNumberC property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setPONumberC(String value) {
            this.poNumberC = value;
        }

        /**
         * Gets the value of the packingInstructionsC property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getPackingInstructionsC() {
            return packingInstructionsC;
        }

        /**
         * Sets the value of the packingInstructionsC property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setPackingInstructionsC(String value) {
            this.packingInstructionsC = value;
        }

        /**
         * Gets the value of the paymentTermsC property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getPaymentTermsC() {
            return paymentTermsC;
        }

        /**
         * Sets the value of the paymentTermsC property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setPaymentTermsC(String value) {
            this.paymentTermsC = value;
        }

        /**
         * Gets the value of the poLineNumberC property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getPoLineNumberC() {
            return poLineNumberC;
        }

        /**
         * Sets the value of the poLineNumberC property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setPoLineNumberC(String value) {
            this.poLineNumberC = value;
        }

        /**
         * Gets the value of the priceDateC property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getPriceDateC() {
            return priceDateC;
        }

        /**
         * Sets the value of the priceDateC property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setPriceDateC(String value) {
            this.priceDateC = value;
        }

        /**
         * Gets the value of the pricelistNameC property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getPricelistNameC() {
            return pricelistNameC;
        }

        /**
         * Sets the value of the pricelistNameC property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setPricelistNameC(String value) {
            this.pricelistNameC = value;
        }

        /**
         * Gets the value of the primarySalesRepNameC property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getPrimarySalesRepNameC() {
            return primarySalesRepNameC;
        }

        /**
         * Sets the value of the primarySalesRepNameC property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setPrimarySalesRepNameC(String value) {
            this.primarySalesRepNameC = value;
        }

        /**
         * Gets the value of the returnReasonCodeC property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getReturnReasonCodeC() {
            return returnReasonCodeC;
        }

        /**
         * Sets the value of the returnReasonCodeC property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setReturnReasonCodeC(String value) {
            this.returnReasonCodeC = value;
        }

        /**
         * Gets the value of the soaEmailC property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getSOAEmailC() {
            return soaEmailC;
        }

        /**
         * Sets the value of the soaEmailC property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setSOAEmailC(String value) {
            this.soaEmailC = value;
        }

        /**
         * Gets the value of the salesProgramC property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getSalesProgramC() {
            return salesProgramC;
        }

        /**
         * Sets the value of the salesProgramC property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setSalesProgramC(String value) {
            this.salesProgramC = value;
        }

        /**
         * Gets the value of the shipPartialFlagC property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getShipPartialFlagC() {
            return shipPartialFlagC;
        }

        /**
         * Sets the value of the shipPartialFlagC property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setShipPartialFlagC(String value) {
            this.shipPartialFlagC = value;
        }

        /**
         * Gets the value of the shipToLocCodeC property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getShipToLocCodeC() {
            return shipToLocCodeC;
        }

        /**
         * Sets the value of the shipToLocCodeC property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setShipToLocCodeC(String value) {
            this.shipToLocCodeC = value;
        }

        /**
         * Gets the value of the shippingAmountC property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getShippingAmountC() {
            return shippingAmountC;
        }

        /**
         * Sets the value of the shippingAmountC property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setShippingAmountC(String value) {
            this.shippingAmountC = value;
        }

        /**
         * Gets the value of the shippingInstructionsC property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getShippingInstructionsC() {
            return shippingInstructionsC;
        }

        /**
         * Sets the value of the shippingInstructionsC property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setShippingInstructionsC(String value) {
            this.shippingInstructionsC = value;
        }

        /**
         * Gets the value of the taxStateC property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getTaxStateC() {
            return taxStateC;
        }

        /**
         * Sets the value of the taxStateC property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setTaxStateC(String value) {
            this.taxStateC = value;
        }

        /**
         * Gets the value of the uomc property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getUOMC() {
            return uomc;
        }

        /**
         * Sets the value of the uomc property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setUOMC(String value) {
            this.uomc = value;
        }

        /**
         * Gets the value of the unitPriceC property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public String getUnitPriceC() {
            return unitPriceC;
        }

        /**
         * Sets the value of the unitPriceC property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setUnitPriceC(String value) {
            this.unitPriceC = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PO_Number__c" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "poNumberC"
    })
    public static class QueryPONumberOutput {

        @XmlElement(name = "PO_Number__c")
        protected List<String> poNumberC;

        /**
         * Gets the value of the poNumberC property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the poNumberC property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPONumberC().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getPONumberC() {
            if (poNumberC == null) {
                poNumberC = new ArrayList<String>();
            }
            return this.poNumberC;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="errors" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="success" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "errors",
        "id",
        "success"
    })
    public static class UpdateInterfaceStatusOutput {

        protected String errors;
        protected String id;
        protected String success;

        /**
         * Gets the value of the errors property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getErrors() {
            return errors;
        }

        /**
         * Sets the value of the errors property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setErrors(String value) {
            this.errors = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the success property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSuccess() {
            return success;
        }

        /**
         * Sets the value of the success property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSuccess(String value) {
            this.success = value;
        }

    }

}
