//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.22 at 01:05:02 PM IST 
//


package com.arris.sfdc.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Operation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="QueryProduct2Input" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ITEM_NUMBER" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="QueryPriceListInput" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PRICE_LIST_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="QueryPriceListLineInput" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="External_ID__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="UpsertPriceListInput" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CurrencyIsoCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Unit_Price__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Product__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="External_ID__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Price_List__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DeletePriceListLineInput" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PRICE_LIST_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "operation",
    "queryProduct2Input",
    "queryPriceListInput",
    "queryPriceListLineInput",
    "upsertPriceListInput",
    "deletePriceListLineInput"
})
@XmlRootElement(name = "PriceBookInput")
public class PriceBookInput {

    @XmlElement(name = "Operation")
    protected String operation;
    @XmlElement(name = "QueryProduct2Input")
    protected PriceBookInput.QueryProduct2Input queryProduct2Input;
    @XmlElement(name = "QueryPriceListInput")
    protected PriceBookInput.QueryPriceListInput queryPriceListInput;
    @XmlElement(name = "QueryPriceListLineInput")
    protected PriceBookInput.QueryPriceListLineInput queryPriceListLineInput;
    @XmlElement(name = "UpsertPriceListInput")
    protected PriceBookInput.UpsertPriceListInput upsertPriceListInput;
    @XmlElement(name = "DeletePriceListLineInput")
    protected PriceBookInput.DeletePriceListLineInput deletePriceListLineInput;

    /**
     * Gets the value of the operation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperation() {
        return operation;
    }

    /**
     * Sets the value of the operation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperation(String value) {
        this.operation = value;
    }

    /**
     * Gets the value of the queryProduct2Input property.
     * 
     * @return
     *     possible object is
     *     {@link PriceBookInput.QueryProduct2Input }
     *     
     */
    public PriceBookInput.QueryProduct2Input getQueryProduct2Input() {
        return queryProduct2Input;
    }

    /**
     * Sets the value of the queryProduct2Input property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceBookInput.QueryProduct2Input }
     *     
     */
    public void setQueryProduct2Input(PriceBookInput.QueryProduct2Input value) {
        this.queryProduct2Input = value;
    }

    /**
     * Gets the value of the queryPriceListInput property.
     * 
     * @return
     *     possible object is
     *     {@link PriceBookInput.QueryPriceListInput }
     *     
     */
    public PriceBookInput.QueryPriceListInput getQueryPriceListInput() {
        return queryPriceListInput;
    }

    /**
     * Sets the value of the queryPriceListInput property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceBookInput.QueryPriceListInput }
     *     
     */
    public void setQueryPriceListInput(PriceBookInput.QueryPriceListInput value) {
        this.queryPriceListInput = value;
    }

    /**
     * Gets the value of the queryPriceListLineInput property.
     * 
     * @return
     *     possible object is
     *     {@link PriceBookInput.QueryPriceListLineInput }
     *     
     */
    public PriceBookInput.QueryPriceListLineInput getQueryPriceListLineInput() {
        return queryPriceListLineInput;
    }

    /**
     * Sets the value of the queryPriceListLineInput property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceBookInput.QueryPriceListLineInput }
     *     
     */
    public void setQueryPriceListLineInput(PriceBookInput.QueryPriceListLineInput value) {
        this.queryPriceListLineInput = value;
    }

    /**
     * Gets the value of the upsertPriceListInput property.
     * 
     * @return
     *     possible object is
     *     {@link PriceBookInput.UpsertPriceListInput }
     *     
     */
    public PriceBookInput.UpsertPriceListInput getUpsertPriceListInput() {
        return upsertPriceListInput;
    }

    /**
     * Sets the value of the upsertPriceListInput property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceBookInput.UpsertPriceListInput }
     *     
     */
    public void setUpsertPriceListInput(PriceBookInput.UpsertPriceListInput value) {
        this.upsertPriceListInput = value;
    }

    /**
     * Gets the value of the deletePriceListLineInput property.
     * 
     * @return
     *     possible object is
     *     {@link PriceBookInput.DeletePriceListLineInput }
     *     
     */
    public PriceBookInput.DeletePriceListLineInput getDeletePriceListLineInput() {
        return deletePriceListLineInput;
    }

    /**
     * Sets the value of the deletePriceListLineInput property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceBookInput.DeletePriceListLineInput }
     *     
     */
    public void setDeletePriceListLineInput(PriceBookInput.DeletePriceListLineInput value) {
        this.deletePriceListLineInput = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PRICE_LIST_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "pricelistid"
    })
    public static class DeletePriceListLineInput {

        @XmlElement(name = "PRICE_LIST_ID")
        protected String pricelistid;

        /**
         * Gets the value of the pricelistid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPRICELISTID() {
            return pricelistid;
        }

        /**
         * Sets the value of the pricelistid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPRICELISTID(String value) {
            this.pricelistid = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PRICE_LIST_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "pricelistid"
    })
    public static class QueryPriceListInput {

        @XmlElement(name = "PRICE_LIST_ID")
        protected String pricelistid;

        /**
         * Gets the value of the pricelistid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPRICELISTID() {
            return pricelistid;
        }

        /**
         * Sets the value of the pricelistid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPRICELISTID(String value) {
            this.pricelistid = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="External_ID__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "externalIDC"
    })
    public static class QueryPriceListLineInput {

        @XmlElement(name = "External_ID__c")
        protected String externalIDC;

        /**
         * Gets the value of the externalIDC property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExternalIDC() {
            return externalIDC;
        }

        /**
         * Sets the value of the externalIDC property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExternalIDC(String value) {
            this.externalIDC = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ITEM_NUMBER" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "itemnumber"
    })
    public static class QueryProduct2Input {

        @XmlElement(name = "ITEM_NUMBER")
        protected String itemnumber;

        /**
         * Gets the value of the itemnumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getITEMNUMBER() {
            return itemnumber;
        }

        /**
         * Sets the value of the itemnumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setITEMNUMBER(String value) {
            this.itemnumber = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CurrencyIsoCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Unit_Price__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Product__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="External_ID__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Price_List__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "currencyIsoCode",
        "unitPriceC",
        "productC",
        "name",
        "externalIDC",
        "priceListC"
    })
    public static class UpsertPriceListInput {

        @XmlElement(name = "CurrencyIsoCode")
        protected String currencyIsoCode;
        @XmlElement(name = "Unit_Price__c")
        protected String unitPriceC;
        @XmlElement(name = "Product__c")
        protected String productC;
        @XmlElement(name = "Name")
        protected String name;
        @XmlElement(name = "External_ID__c")
        protected String externalIDC;
        @XmlElement(name = "Price_List__c")
        protected String priceListC;

        /**
         * Gets the value of the currencyIsoCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCurrencyIsoCode() {
            return currencyIsoCode;
        }

        /**
         * Sets the value of the currencyIsoCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCurrencyIsoCode(String value) {
            this.currencyIsoCode = value;
        }

        /**
         * Gets the value of the unitPriceC property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUnitPriceC() {
            return unitPriceC;
        }

        /**
         * Sets the value of the unitPriceC property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUnitPriceC(String value) {
            this.unitPriceC = value;
        }

        /**
         * Gets the value of the productC property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProductC() {
            return productC;
        }

        /**
         * Sets the value of the productC property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProductC(String value) {
            this.productC = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the externalIDC property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExternalIDC() {
            return externalIDC;
        }

        /**
         * Sets the value of the externalIDC property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExternalIDC(String value) {
            this.externalIDC = value;
        }

        /**
         * Gets the value of the priceListC property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPriceListC() {
            return priceListC;
        }

        /**
         * Sets the value of the priceListC property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPriceListC(String value) {
            this.priceListC = value;
        }

    }

}
