//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.22 at 01:05:02 PM IST 
//


package com.arris.sfdc.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="QueryProduct2Output" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="QueryPriceListOutput" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="QueryPriceListLineOutput" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="UpsertPriceListOutput" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="errors" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="success" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DeletePriceListLineOutput" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="errors" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="success" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "queryProduct2Output",
    "queryPriceListOutput",
    "queryPriceListLineOutput",
    "upsertPriceListOutput",
    "deletePriceListLineOutput"
})
@XmlRootElement(name = "PriceBookOutput")
public class PriceBookOutput {

    @XmlElement(name = "QueryProduct2Output")
    protected PriceBookOutput.QueryProduct2Output queryProduct2Output;
    @XmlElement(name = "QueryPriceListOutput")
    protected PriceBookOutput.QueryPriceListOutput queryPriceListOutput;
    @XmlElement(name = "QueryPriceListLineOutput")
    protected PriceBookOutput.QueryPriceListLineOutput queryPriceListLineOutput;
    @XmlElement(name = "UpsertPriceListOutput")
    protected PriceBookOutput.UpsertPriceListOutput upsertPriceListOutput;
    @XmlElement(name = "DeletePriceListLineOutput")
    protected PriceBookOutput.DeletePriceListLineOutput deletePriceListLineOutput;

    /**
     * Gets the value of the queryProduct2Output property.
     * 
     * @return
     *     possible object is
     *     {@link PriceBookOutput.QueryProduct2Output }
     *     
     */
    public PriceBookOutput.QueryProduct2Output getQueryProduct2Output() {
        return queryProduct2Output;
    }

    /**
     * Sets the value of the queryProduct2Output property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceBookOutput.QueryProduct2Output }
     *     
     */
    public void setQueryProduct2Output(PriceBookOutput.QueryProduct2Output value) {
        this.queryProduct2Output = value;
    }

    /**
     * Gets the value of the queryPriceListOutput property.
     * 
     * @return
     *     possible object is
     *     {@link PriceBookOutput.QueryPriceListOutput }
     *     
     */
    public PriceBookOutput.QueryPriceListOutput getQueryPriceListOutput() {
        return queryPriceListOutput;
    }

    /**
     * Sets the value of the queryPriceListOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceBookOutput.QueryPriceListOutput }
     *     
     */
    public void setQueryPriceListOutput(PriceBookOutput.QueryPriceListOutput value) {
        this.queryPriceListOutput = value;
    }

    /**
     * Gets the value of the queryPriceListLineOutput property.
     * 
     * @return
     *     possible object is
     *     {@link PriceBookOutput.QueryPriceListLineOutput }
     *     
     */
    public PriceBookOutput.QueryPriceListLineOutput getQueryPriceListLineOutput() {
        return queryPriceListLineOutput;
    }

    /**
     * Sets the value of the queryPriceListLineOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceBookOutput.QueryPriceListLineOutput }
     *     
     */
    public void setQueryPriceListLineOutput(PriceBookOutput.QueryPriceListLineOutput value) {
        this.queryPriceListLineOutput = value;
    }

    /**
     * Gets the value of the upsertPriceListOutput property.
     * 
     * @return
     *     possible object is
     *     {@link PriceBookOutput.UpsertPriceListOutput }
     *     
     */
    public PriceBookOutput.UpsertPriceListOutput getUpsertPriceListOutput() {
        return upsertPriceListOutput;
    }

    /**
     * Sets the value of the upsertPriceListOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceBookOutput.UpsertPriceListOutput }
     *     
     */
    public void setUpsertPriceListOutput(PriceBookOutput.UpsertPriceListOutput value) {
        this.upsertPriceListOutput = value;
    }

    /**
     * Gets the value of the deletePriceListLineOutput property.
     * 
     * @return
     *     possible object is
     *     {@link PriceBookOutput.DeletePriceListLineOutput }
     *     
     */
    public PriceBookOutput.DeletePriceListLineOutput getDeletePriceListLineOutput() {
        return deletePriceListLineOutput;
    }

    /**
     * Sets the value of the deletePriceListLineOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceBookOutput.DeletePriceListLineOutput }
     *     
     */
    public void setDeletePriceListLineOutput(PriceBookOutput.DeletePriceListLineOutput value) {
        this.deletePriceListLineOutput = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="errors" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="success" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "errors",
        "id",
        "success"
    })
    public static class DeletePriceListLineOutput {

        protected String errors;
        protected String id;
        protected String success;

        /**
         * Gets the value of the errors property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getErrors() {
            return errors;
        }

        /**
         * Sets the value of the errors property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setErrors(String value) {
            this.errors = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the success property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSuccess() {
            return success;
        }

        /**
         * Sets the value of the success property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSuccess(String value) {
            this.success = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id"
    })
    public static class QueryPriceListLineOutput {

        @XmlElement(name = "Id")
        protected String id;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id"
    })
    public static class QueryPriceListOutput {

        @XmlElement(name = "Id")
        protected String id;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "name"
    })
    public static class QueryProduct2Output {

        @XmlElement(name = "Id")
        protected String id;
        @XmlElement(name = "Name")
        protected String name;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="errors" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="success" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "errors",
        "id",
        "success"
    })
    public static class UpsertPriceListOutput {

        protected String errors;
        protected String id;
        protected String success;

        /**
         * Gets the value of the errors property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getErrors() {
            return errors;
        }

        /**
         * Sets the value of the errors property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setErrors(String value) {
            this.errors = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the success property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSuccess() {
            return success;
        }

        /**
         * Sets the value of the success property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSuccess(String value) {
            this.success = value;
        }

    }

}
