//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.27 at 02:15:47 PM IST 
//


package com.arris.sfdc.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="QueryAPCOutput" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="QueryProductSBUOutput" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="QueryProductTechnologyOutput" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="QueryProductFamilyOutput" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="QueryProductLineOutput" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="QueryProductClassOutput" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="QueryProductCodeOutput" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "queryAPCOutput",
    "queryProductSBUOutput",
    "queryProductTechnologyOutput",
    "queryProductFamilyOutput",
    "queryProductLineOutput",
    "queryProductClassOutput",
    "queryProductCodeOutput"
})
@XmlRootElement(name = "QueryProductOutput")
public class QueryProductOutput {

    @XmlElement(name = "QueryAPCOutput")
    protected QueryProductOutput.QueryAPCOutput queryAPCOutput;
    @XmlElement(name = "QueryProductSBUOutput")
    protected QueryProductOutput.QueryProductSBUOutput queryProductSBUOutput;
    @XmlElement(name = "QueryProductTechnologyOutput")
    protected QueryProductOutput.QueryProductTechnologyOutput queryProductTechnologyOutput;
    @XmlElement(name = "QueryProductFamilyOutput")
    protected QueryProductOutput.QueryProductFamilyOutput queryProductFamilyOutput;
    @XmlElement(name = "QueryProductLineOutput")
    protected QueryProductOutput.QueryProductLineOutput queryProductLineOutput;
    @XmlElement(name = "QueryProductClassOutput")
    protected QueryProductOutput.QueryProductClassOutput queryProductClassOutput;
    @XmlElement(name = "QueryProductCodeOutput")
    protected QueryProductOutput.QueryProductCodeOutput queryProductCodeOutput;

    /**
     * Gets the value of the queryAPCOutput property.
     * 
     * @return
     *     possible object is
     *     {@link QueryProductOutput.QueryAPCOutput }
     *     
     */
    public QueryProductOutput.QueryAPCOutput getQueryAPCOutput() {
        return queryAPCOutput;
    }

    /**
     * Sets the value of the queryAPCOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryProductOutput.QueryAPCOutput }
     *     
     */
    public void setQueryAPCOutput(QueryProductOutput.QueryAPCOutput value) {
        this.queryAPCOutput = value;
    }

    /**
     * Gets the value of the queryProductSBUOutput property.
     * 
     * @return
     *     possible object is
     *     {@link QueryProductOutput.QueryProductSBUOutput }
     *     
     */
    public QueryProductOutput.QueryProductSBUOutput getQueryProductSBUOutput() {
        return queryProductSBUOutput;
    }

    /**
     * Sets the value of the queryProductSBUOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryProductOutput.QueryProductSBUOutput }
     *     
     */
    public void setQueryProductSBUOutput(QueryProductOutput.QueryProductSBUOutput value) {
        this.queryProductSBUOutput = value;
    }

    /**
     * Gets the value of the queryProductTechnologyOutput property.
     * 
     * @return
     *     possible object is
     *     {@link QueryProductOutput.QueryProductTechnologyOutput }
     *     
     */
    public QueryProductOutput.QueryProductTechnologyOutput getQueryProductTechnologyOutput() {
        return queryProductTechnologyOutput;
    }

    /**
     * Sets the value of the queryProductTechnologyOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryProductOutput.QueryProductTechnologyOutput }
     *     
     */
    public void setQueryProductTechnologyOutput(QueryProductOutput.QueryProductTechnologyOutput value) {
        this.queryProductTechnologyOutput = value;
    }

    /**
     * Gets the value of the queryProductFamilyOutput property.
     * 
     * @return
     *     possible object is
     *     {@link QueryProductOutput.QueryProductFamilyOutput }
     *     
     */
    public QueryProductOutput.QueryProductFamilyOutput getQueryProductFamilyOutput() {
        return queryProductFamilyOutput;
    }

    /**
     * Sets the value of the queryProductFamilyOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryProductOutput.QueryProductFamilyOutput }
     *     
     */
    public void setQueryProductFamilyOutput(QueryProductOutput.QueryProductFamilyOutput value) {
        this.queryProductFamilyOutput = value;
    }

    /**
     * Gets the value of the queryProductLineOutput property.
     * 
     * @return
     *     possible object is
     *     {@link QueryProductOutput.QueryProductLineOutput }
     *     
     */
    public QueryProductOutput.QueryProductLineOutput getQueryProductLineOutput() {
        return queryProductLineOutput;
    }

    /**
     * Sets the value of the queryProductLineOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryProductOutput.QueryProductLineOutput }
     *     
     */
    public void setQueryProductLineOutput(QueryProductOutput.QueryProductLineOutput value) {
        this.queryProductLineOutput = value;
    }

    /**
     * Gets the value of the queryProductClassOutput property.
     * 
     * @return
     *     possible object is
     *     {@link QueryProductOutput.QueryProductClassOutput }
     *     
     */
    public QueryProductOutput.QueryProductClassOutput getQueryProductClassOutput() {
        return queryProductClassOutput;
    }

    /**
     * Sets the value of the queryProductClassOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryProductOutput.QueryProductClassOutput }
     *     
     */
    public void setQueryProductClassOutput(QueryProductOutput.QueryProductClassOutput value) {
        this.queryProductClassOutput = value;
    }

    /**
     * Gets the value of the queryProductCodeOutput property.
     * 
     * @return
     *     possible object is
     *     {@link QueryProductOutput.QueryProductCodeOutput }
     *     
     */
    public QueryProductOutput.QueryProductCodeOutput getQueryProductCodeOutput() {
        return queryProductCodeOutput;
    }

    /**
     * Sets the value of the queryProductCodeOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryProductOutput.QueryProductCodeOutput }
     *     
     */
    public void setQueryProductCodeOutput(QueryProductOutput.QueryProductCodeOutput value) {
        this.queryProductCodeOutput = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id"
    })
    public static class QueryAPCOutput {

        @XmlElement(name = "Id")
        protected String id;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id"
    })
    public static class QueryProductClassOutput {

        @XmlElement(name = "Id")
        protected String id;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id"
    })
    public static class QueryProductCodeOutput {

        @XmlElement(name = "Id")
        protected String id;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id"
    })
    public static class QueryProductFamilyOutput {

        @XmlElement(name = "Id")
        protected String id;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id"
    })
    public static class QueryProductLineOutput {

        @XmlElement(name = "Id")
        protected String id;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id"
    })
    public static class QueryProductSBUOutput {

        @XmlElement(name = "Id")
        protected String id;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id"
    })
    public static class QueryProductTechnologyOutput {

        @XmlElement(name = "Id")
        protected String id;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

    }

}
