//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.20 at 01:03:25 PM IST 
//


package com.arris.sfdc.pojo;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Inputs" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Dept__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Department_Description__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Department_Entity__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Department_BU__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Accounting_Code__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="IsActive__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "inputs"
})
@XmlRootElement(name = "UpsertDepts")
public class UpsertDepts{

    @XmlElement(name = "Inputs", required = true)
    protected List<UpsertDepts.Inputs> inputs;

    /**
     * Gets the value of the inputs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inputs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInputs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UpsertDepts.Inputs }
     * 
     * 
     */
    public List<UpsertDepts.Inputs> getInputs() {
        if (inputs == null) {
            inputs = new ArrayList<UpsertDepts.Inputs>();
        }
        return this.inputs;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Dept__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Department_Description__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Department_Entity__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Department_BU__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Accounting_Code__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="IsActive__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "deptC",
        "name",
        "departmentDescriptionC",
        "departmentEntityC",
        "departmentBUC",
        "accountingCodeC",
        "isActiveC"
    })
    public static class Inputs{
        @XmlElement(name = "Dept__c")
        protected String deptC;
        @XmlElement(name = "Name")
        protected String name;
        @XmlElement(name = "Department_Description__c")
        protected String departmentDescriptionC;
        @XmlElement(name = "Department_Entity__c")
        protected String departmentEntityC;
        @XmlElement(name = "Department_BU__c")
        protected String departmentBUC;
        @XmlElement(name = "Accounting_Code__c")
        protected String accountingCodeC;
        @XmlElement(name = "IsActive__c")
        protected String isActiveC;

        /**
         * Gets the value of the deptC property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDeptC() {
            return deptC;
        }

        /**
         * Sets the value of the deptC property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDeptC(String value) {
            this.deptC = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the departmentDescriptionC property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDepartmentDescriptionC() {
        	System.out.println("Called Dept Get : "+departmentDescriptionC);
            return departmentDescriptionC;
        }

        /**
         * Sets the value of the departmentDescriptionC property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDepartmentDescriptionC(String value) {
        	System.out.println("Called Dept set");
            this.departmentDescriptionC = value;
        }

        /**
         * Gets the value of the departmentEntityC property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDepartmentEntityC() {
            return departmentEntityC;
        }

        /**
         * Sets the value of the departmentEntityC property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDepartmentEntityC(String value) {
            this.departmentEntityC = value;
        }

        /**
         * Gets the value of the departmentBUC property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDepartmentBUC() {
            return departmentBUC;
        }

        /**
         * Sets the value of the departmentBUC property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDepartmentBUC(String value) {
            this.departmentBUC = value;
        }

        /**
         * Gets the value of the accountingCodeC property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAccountingCodeC() {
            return accountingCodeC;
        }

        /**
         * Sets the value of the accountingCodeC property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAccountingCodeC(String value) {
            this.accountingCodeC = value;
        }

        /**
         * Gets the value of the isActiveC property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIsActiveC() {
            return isActiveC;
        }

        /**
         * Sets the value of the isActiveC property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIsActiveC(String value) {
            this.isActiveC = value;
        }
    }
}
