//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.03 at 12:36:42 PM IST 
//


package com.arris.sfdc.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UpsertProductAPCOutput" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="errors" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="success" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="UpsertProductSBUOutput" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="errors" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="success" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="UpsertProductTechnologyOutput" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="errors" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="success" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="UpsertProductFamilyOutput" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="errors" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="success" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="UpsertProductLineOutput" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="errors" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="success" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="UpsertProductClassOutput" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="errors" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="success" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="UpsertProductCodeOutput" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="errors" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="success" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "upsertProductAPCOutput",
    "upsertProductSBUOutput",
    "upsertProductTechnologyOutput",
    "upsertProductFamilyOutput",
    "upsertProductLineOutput",
    "upsertProductClassOutput",
    "upsertProductCodeOutput"
})
@XmlRootElement(name = "UpsertProductOutput")
public class UpsertProductOutput {

    @XmlElement(name = "UpsertProductAPCOutput")
    protected UpsertProductOutput.UpsertProductAPCOutput upsertProductAPCOutput;
    @XmlElement(name = "UpsertProductSBUOutput")
    protected UpsertProductOutput.UpsertProductSBUOutput upsertProductSBUOutput;
    @XmlElement(name = "UpsertProductTechnologyOutput")
    protected UpsertProductOutput.UpsertProductTechnologyOutput upsertProductTechnologyOutput;
    @XmlElement(name = "UpsertProductFamilyOutput")
    protected UpsertProductOutput.UpsertProductFamilyOutput upsertProductFamilyOutput;
    @XmlElement(name = "UpsertProductLineOutput")
    protected UpsertProductOutput.UpsertProductLineOutput upsertProductLineOutput;
    @XmlElement(name = "UpsertProductClassOutput")
    protected UpsertProductOutput.UpsertProductClassOutput upsertProductClassOutput;
    @XmlElement(name = "UpsertProductCodeOutput")
    protected UpsertProductOutput.UpsertProductCodeOutput upsertProductCodeOutput;

    /**
     * Gets the value of the upsertProductAPCOutput property.
     * 
     * @return
     *     possible object is
     *     {@link UpsertProductOutput.UpsertProductAPCOutput }
     *     
     */
    public UpsertProductOutput.UpsertProductAPCOutput getUpsertProductAPCOutput() {
        return upsertProductAPCOutput;
    }

    /**
     * Sets the value of the upsertProductAPCOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpsertProductOutput.UpsertProductAPCOutput }
     *     
     */
    public void setUpsertProductAPCOutput(UpsertProductOutput.UpsertProductAPCOutput value) {
        this.upsertProductAPCOutput = value;
    }

    /**
     * Gets the value of the upsertProductSBUOutput property.
     * 
     * @return
     *     possible object is
     *     {@link UpsertProductOutput.UpsertProductSBUOutput }
     *     
     */
    public UpsertProductOutput.UpsertProductSBUOutput getUpsertProductSBUOutput() {
        return upsertProductSBUOutput;
    }

    /**
     * Sets the value of the upsertProductSBUOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpsertProductOutput.UpsertProductSBUOutput }
     *     
     */
    public void setUpsertProductSBUOutput(UpsertProductOutput.UpsertProductSBUOutput value) {
        this.upsertProductSBUOutput = value;
    }

    /**
     * Gets the value of the upsertProductTechnologyOutput property.
     * 
     * @return
     *     possible object is
     *     {@link UpsertProductOutput.UpsertProductTechnologyOutput }
     *     
     */
    public UpsertProductOutput.UpsertProductTechnologyOutput getUpsertProductTechnologyOutput() {
        return upsertProductTechnologyOutput;
    }

    /**
     * Sets the value of the upsertProductTechnologyOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpsertProductOutput.UpsertProductTechnologyOutput }
     *     
     */
    public void setUpsertProductTechnologyOutput(UpsertProductOutput.UpsertProductTechnologyOutput value) {
        this.upsertProductTechnologyOutput = value;
    }

    /**
     * Gets the value of the upsertProductFamilyOutput property.
     * 
     * @return
     *     possible object is
     *     {@link UpsertProductOutput.UpsertProductFamilyOutput }
     *     
     */
    public UpsertProductOutput.UpsertProductFamilyOutput getUpsertProductFamilyOutput() {
        return upsertProductFamilyOutput;
    }

    /**
     * Sets the value of the upsertProductFamilyOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpsertProductOutput.UpsertProductFamilyOutput }
     *     
     */
    public void setUpsertProductFamilyOutput(UpsertProductOutput.UpsertProductFamilyOutput value) {
        this.upsertProductFamilyOutput = value;
    }

    /**
     * Gets the value of the upsertProductLineOutput property.
     * 
     * @return
     *     possible object is
     *     {@link UpsertProductOutput.UpsertProductLineOutput }
     *     
     */
    public UpsertProductOutput.UpsertProductLineOutput getUpsertProductLineOutput() {
        return upsertProductLineOutput;
    }

    /**
     * Sets the value of the upsertProductLineOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpsertProductOutput.UpsertProductLineOutput }
     *     
     */
    public void setUpsertProductLineOutput(UpsertProductOutput.UpsertProductLineOutput value) {
        this.upsertProductLineOutput = value;
    }

    /**
     * Gets the value of the upsertProductClassOutput property.
     * 
     * @return
     *     possible object is
     *     {@link UpsertProductOutput.UpsertProductClassOutput }
     *     
     */
    public UpsertProductOutput.UpsertProductClassOutput getUpsertProductClassOutput() {
        return upsertProductClassOutput;
    }

    /**
     * Sets the value of the upsertProductClassOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpsertProductOutput.UpsertProductClassOutput }
     *     
     */
    public void setUpsertProductClassOutput(UpsertProductOutput.UpsertProductClassOutput value) {
        this.upsertProductClassOutput = value;
    }

    /**
     * Gets the value of the upsertProductCodeOutput property.
     * 
     * @return
     *     possible object is
     *     {@link UpsertProductOutput.UpsertProductCodeOutput }
     *     
     */
    public UpsertProductOutput.UpsertProductCodeOutput getUpsertProductCodeOutput() {
        return upsertProductCodeOutput;
    }

    /**
     * Sets the value of the upsertProductCodeOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpsertProductOutput.UpsertProductCodeOutput }
     *     
     */
    public void setUpsertProductCodeOutput(UpsertProductOutput.UpsertProductCodeOutput value) {
        this.upsertProductCodeOutput = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="errors" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="success" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "errors",
        "id",
        "success"
    })
    public static class UpsertProductAPCOutput {

        protected String errors;
        protected String id;
        protected String success;

        /**
         * Gets the value of the errors property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getErrors() {
            return errors;
        }

        /**
         * Sets the value of the errors property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setErrors(String value) {
            this.errors = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the success property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSuccess() {
            return success;
        }

        /**
         * Sets the value of the success property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSuccess(String value) {
            this.success = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="errors" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="success" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "errors",
        "id",
        "success"
    })
    public static class UpsertProductClassOutput {

        protected String errors;
        protected String id;
        protected String success;

        /**
         * Gets the value of the errors property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getErrors() {
            return errors;
        }

        /**
         * Sets the value of the errors property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setErrors(String value) {
            this.errors = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the success property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSuccess() {
            return success;
        }

        /**
         * Sets the value of the success property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSuccess(String value) {
            this.success = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="errors" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="success" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "errors",
        "id",
        "success"
    })
    public static class UpsertProductCodeOutput {

        protected String errors;
        protected String id;
        protected String success;

        /**
         * Gets the value of the errors property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getErrors() {
            return errors;
        }

        /**
         * Sets the value of the errors property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setErrors(String value) {
            this.errors = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the success property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSuccess() {
            return success;
        }

        /**
         * Sets the value of the success property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSuccess(String value) {
            this.success = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="errors" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="success" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "errors",
        "id",
        "success"
    })
    public static class UpsertProductFamilyOutput {

        protected String errors;
        protected String id;
        protected String success;

        /**
         * Gets the value of the errors property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getErrors() {
            return errors;
        }

        /**
         * Sets the value of the errors property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setErrors(String value) {
            this.errors = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the success property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSuccess() {
            return success;
        }

        /**
         * Sets the value of the success property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSuccess(String value) {
            this.success = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="errors" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="success" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "errors",
        "id",
        "success"
    })
    public static class UpsertProductLineOutput {

        protected String errors;
        protected String id;
        protected String success;

        /**
         * Gets the value of the errors property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getErrors() {
            return errors;
        }

        /**
         * Sets the value of the errors property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setErrors(String value) {
            this.errors = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the success property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSuccess() {
            return success;
        }

        /**
         * Sets the value of the success property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSuccess(String value) {
            this.success = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="errors" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="success" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "errors",
        "id",
        "success"
    })
    public static class UpsertProductSBUOutput {

        protected String errors;
        protected String id;
        protected String success;

        /**
         * Gets the value of the errors property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getErrors() {
            return errors;
        }

        /**
         * Sets the value of the errors property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setErrors(String value) {
            this.errors = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the success property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSuccess() {
            return success;
        }

        /**
         * Sets the value of the success property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSuccess(String value) {
            this.success = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="errors" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="success" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "errors",
        "id",
        "success"
    })
    public static class UpsertProductTechnologyOutput {

        protected String errors;
        protected String id;
        protected String success;

        /**
         * Gets the value of the errors property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getErrors() {
            return errors;
        }

        /**
         * Sets the value of the errors property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setErrors(String value) {
            this.errors = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the success property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSuccess() {
            return success;
        }

        /**
         * Sets the value of the success property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSuccess(String value) {
            this.success = value;
        }

    }

}
