//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.03 at 12:36:42 PM IST 
//


package com.arris.sfdc.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Operation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UpsertProductAPCInput" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Name__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Description__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="UpsertProductSBUInput" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Name__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="UpsertProductTechnologyInput" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Name__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="UpsertProductFamilyInput" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Name__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="UpsertProductLineInput" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Name__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="UpsertProductClassInput" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Name__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="UpsertProductCodeInput" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Name__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "operation",
    "upsertProductAPCInput",
    "upsertProductSBUInput",
    "upsertProductTechnologyInput",
    "upsertProductFamilyInput",
    "upsertProductLineInput",
    "upsertProductClassInput",
    "upsertProductCodeInput"
})
@XmlRootElement(name = "UpsertProductInput")
public class UpsertProductInput {

    @XmlElement(name = "Operation")
    protected String operation;
    @XmlElement(name = "UpsertProductAPCInput")
    protected UpsertProductInput.UpsertProductAPCInput upsertProductAPCInput;
    @XmlElement(name = "UpsertProductSBUInput")
    protected UpsertProductInput.UpsertProductSBUInput upsertProductSBUInput;
    @XmlElement(name = "UpsertProductTechnologyInput")
    protected UpsertProductInput.UpsertProductTechnologyInput upsertProductTechnologyInput;
    @XmlElement(name = "UpsertProductFamilyInput")
    protected UpsertProductInput.UpsertProductFamilyInput upsertProductFamilyInput;
    @XmlElement(name = "UpsertProductLineInput")
    protected UpsertProductInput.UpsertProductLineInput upsertProductLineInput;
    @XmlElement(name = "UpsertProductClassInput")
    protected UpsertProductInput.UpsertProductClassInput upsertProductClassInput;
    @XmlElement(name = "UpsertProductCodeInput")
    protected UpsertProductInput.UpsertProductCodeInput upsertProductCodeInput;

    /**
     * Gets the value of the operation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperation() {
        return operation;
    }

    /**
     * Sets the value of the operation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperation(String value) {
        this.operation = value;
    }

    /**
     * Gets the value of the upsertProductAPCInput property.
     * 
     * @return
     *     possible object is
     *     {@link UpsertProductInput.UpsertProductAPCInput }
     *     
     */
    public UpsertProductInput.UpsertProductAPCInput getUpsertProductAPCInput() {
        return upsertProductAPCInput;
    }

    /**
     * Sets the value of the upsertProductAPCInput property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpsertProductInput.UpsertProductAPCInput }
     *     
     */
    public void setUpsertProductAPCInput(UpsertProductInput.UpsertProductAPCInput value) {
        this.upsertProductAPCInput = value;
    }

    /**
     * Gets the value of the upsertProductSBUInput property.
     * 
     * @return
     *     possible object is
     *     {@link UpsertProductInput.UpsertProductSBUInput }
     *     
     */
    public UpsertProductInput.UpsertProductSBUInput getUpsertProductSBUInput() {
        return upsertProductSBUInput;
    }

    /**
     * Sets the value of the upsertProductSBUInput property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpsertProductInput.UpsertProductSBUInput }
     *     
     */
    public void setUpsertProductSBUInput(UpsertProductInput.UpsertProductSBUInput value) {
        this.upsertProductSBUInput = value;
    }

    /**
     * Gets the value of the upsertProductTechnologyInput property.
     * 
     * @return
     *     possible object is
     *     {@link UpsertProductInput.UpsertProductTechnologyInput }
     *     
     */
    public UpsertProductInput.UpsertProductTechnologyInput getUpsertProductTechnologyInput() {
        return upsertProductTechnologyInput;
    }

    /**
     * Sets the value of the upsertProductTechnologyInput property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpsertProductInput.UpsertProductTechnologyInput }
     *     
     */
    public void setUpsertProductTechnologyInput(UpsertProductInput.UpsertProductTechnologyInput value) {
        this.upsertProductTechnologyInput = value;
    }

    /**
     * Gets the value of the upsertProductFamilyInput property.
     * 
     * @return
     *     possible object is
     *     {@link UpsertProductInput.UpsertProductFamilyInput }
     *     
     */
    public UpsertProductInput.UpsertProductFamilyInput getUpsertProductFamilyInput() {
        return upsertProductFamilyInput;
    }

    /**
     * Sets the value of the upsertProductFamilyInput property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpsertProductInput.UpsertProductFamilyInput }
     *     
     */
    public void setUpsertProductFamilyInput(UpsertProductInput.UpsertProductFamilyInput value) {
        this.upsertProductFamilyInput = value;
    }

    /**
     * Gets the value of the upsertProductLineInput property.
     * 
     * @return
     *     possible object is
     *     {@link UpsertProductInput.UpsertProductLineInput }
     *     
     */
    public UpsertProductInput.UpsertProductLineInput getUpsertProductLineInput() {
        return upsertProductLineInput;
    }

    /**
     * Sets the value of the upsertProductLineInput property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpsertProductInput.UpsertProductLineInput }
     *     
     */
    public void setUpsertProductLineInput(UpsertProductInput.UpsertProductLineInput value) {
        this.upsertProductLineInput = value;
    }

    /**
     * Gets the value of the upsertProductClassInput property.
     * 
     * @return
     *     possible object is
     *     {@link UpsertProductInput.UpsertProductClassInput }
     *     
     */
    public UpsertProductInput.UpsertProductClassInput getUpsertProductClassInput() {
        return upsertProductClassInput;
    }

    /**
     * Sets the value of the upsertProductClassInput property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpsertProductInput.UpsertProductClassInput }
     *     
     */
    public void setUpsertProductClassInput(UpsertProductInput.UpsertProductClassInput value) {
        this.upsertProductClassInput = value;
    }

    /**
     * Gets the value of the upsertProductCodeInput property.
     * 
     * @return
     *     possible object is
     *     {@link UpsertProductInput.UpsertProductCodeInput }
     *     
     */
    public UpsertProductInput.UpsertProductCodeInput getUpsertProductCodeInput() {
        return upsertProductCodeInput;
    }

    /**
     * Sets the value of the upsertProductCodeInput property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpsertProductInput.UpsertProductCodeInput }
     *     
     */
    public void setUpsertProductCodeInput(UpsertProductInput.UpsertProductCodeInput value) {
        this.upsertProductCodeInput = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Name__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Description__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nameC",
        "descriptionC"
    })
    public static class UpsertProductAPCInput {

        @XmlElement(name = "Name__c")
        protected String nameC;
        @XmlElement(name = "Description__c")
        protected String descriptionC;

        /**
         * Gets the value of the nameC property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNameC() {
            return nameC;
        }

        /**
         * Sets the value of the nameC property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNameC(String value) {
            this.nameC = value;
        }

        /**
         * Gets the value of the descriptionC property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescriptionC() {
            return descriptionC;
        }

        /**
         * Sets the value of the descriptionC property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescriptionC(String value) {
            this.descriptionC = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Name__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nameC"
    })
    public static class UpsertProductClassInput {

        @XmlElement(name = "Name__c")
        protected String nameC;

        /**
         * Gets the value of the nameC property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNameC() {
            return nameC;
        }

        /**
         * Sets the value of the nameC property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNameC(String value) {
            this.nameC = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Name__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "nameC"
    })
    public static class UpsertProductCodeInput {

        @XmlElement(name = "Name")
        protected String name;
        @XmlElement(name = "Name__c")
        protected String nameC;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the nameC property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNameC() {
            return nameC;
        }

        /**
         * Sets the value of the nameC property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNameC(String value) {
            this.nameC = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Name__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nameC"
    })
    public static class UpsertProductFamilyInput {

        @XmlElement(name = "Name__c")
        protected String nameC;

        /**
         * Gets the value of the nameC property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNameC() {
            return nameC;
        }

        /**
         * Sets the value of the nameC property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNameC(String value) {
            this.nameC = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Name__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nameC"
    })
    public static class UpsertProductLineInput {

        @XmlElement(name = "Name__c")
        protected String nameC;

        /**
         * Gets the value of the nameC property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNameC() {
            return nameC;
        }

        /**
         * Sets the value of the nameC property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNameC(String value) {
            this.nameC = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Name__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nameC"
    })
    public static class UpsertProductSBUInput {

        @XmlElement(name = "Name__c")
        protected String nameC;

        /**
         * Gets the value of the nameC property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNameC() {
            return nameC;
        }

        /**
         * Sets the value of the nameC property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNameC(String value) {
            this.nameC = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Name__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nameC"
    })
    public static class UpsertProductTechnologyInput {

        @XmlElement(name = "Name__c")
        protected String nameC;

        /**
         * Gets the value of the nameC property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNameC() {
            return nameC;
        }

        /**
         * Sets the value of the nameC property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNameC(String value) {
            this.nameC = value;
        }

    }

}
