//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.15 at 05:43:55 PM IST 
//


package com.arris.sfdc.pojo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pseMiscellaneousAdjustmentC" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Misc_Adjustment_PS_Key__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Source_Type__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="pse__Effective_Date__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Effective_Date_Integration__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="PO_Number__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="pse__Description__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="pse__Invoice_Number__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="pse__Invoice_Date__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="CurrencyIsoCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="pse__Amount__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="pse__Status__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="pse__Approved__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="pse__Include_In_Financials__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="pse__Transaction_Category__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="pse__Invoiced__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="pse__Billed__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Estimate_Category__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Time_Period__r" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="pse__Project__r" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="pse__Vendor_Account__r" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pseMiscellaneousAdjustmentC"
})
@XmlRootElement(name = "InputElement")
public class InputElement {

    @XmlElement(required = true)
    protected List<InputElement.PseMiscellaneousAdjustmentC> pseMiscellaneousAdjustmentC;

    /**
     * Gets the value of the pseMiscellaneousAdjustmentC property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pseMiscellaneousAdjustmentC property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPseMiscellaneousAdjustmentC().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InputElement.PseMiscellaneousAdjustmentC }
     * 
     * 
     */
    public List<InputElement.PseMiscellaneousAdjustmentC> getPseMiscellaneousAdjustmentC() {
        if (pseMiscellaneousAdjustmentC == null) {
            pseMiscellaneousAdjustmentC = new ArrayList<InputElement.PseMiscellaneousAdjustmentC>();
        }
        return this.pseMiscellaneousAdjustmentC;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Misc_Adjustment_PS_Key__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Source_Type__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="pse__Effective_Date__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Effective_Date_Integration__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="PO_Number__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="pse__Description__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="pse__Invoice_Number__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="pse__Invoice_Date__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="CurrencyIsoCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="pse__Amount__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="pse__Status__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="pse__Approved__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="pse__Include_In_Financials__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="pse__Transaction_Category__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="pse__Invoiced__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="pse__Billed__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Estimate_Category__c" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Time_Period__r" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="pse__Project__r" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="pse__Vendor_Account__r" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "miscAdjustmentPSKeyC",
        "sourceTypeC",
        "pseEffectiveDateC",
        "effectiveDateIntegrationC",
        "poNumberC",
        "pseDescriptionC",
        "pseInvoiceNumberC",
        "pseInvoiceDateC",
        "currencyIsoCode",
        "pseAmountC",
        "name",
        "pseStatusC",
        "pseApprovedC",
        "pseIncludeInFinancialsC",
        "pseTransactionCategoryC",
        "pseInvoicedC",
        "pseBilledC",
        "estimateCategoryC",
        "timePeriodR",
        "pseProjectR",
        "pseVendorAccountR"
    })
    public static class PseMiscellaneousAdjustmentC {

        @XmlElement(name = "Misc_Adjustment_PS_Key__c")
        protected String miscAdjustmentPSKeyC;
        @XmlElement(name = "Source_Type__c")
        protected String sourceTypeC;
        @XmlElement(name = "pse__Effective_Date__c")
        protected String pseEffectiveDateC;
        @XmlElement(name = "Effective_Date_Integration__c")
        protected String effectiveDateIntegrationC;
        @XmlElement(name = "PO_Number__c")
        protected String poNumberC;
        @XmlElement(name = "pse__Description__c")
        protected String pseDescriptionC;
        @XmlElement(name = "pse__Invoice_Number__c")
        protected String pseInvoiceNumberC;
        @XmlElement(name = "pse__Invoice_Date__c")
        protected String pseInvoiceDateC;
        @XmlElement(name = "CurrencyIsoCode")
        protected String currencyIsoCode;
        @XmlElement(name = "pse__Amount__c")
        protected String pseAmountC;
        @XmlElement(name = "Name")
        protected String name;
        @XmlElement(name = "pse__Status__c")
        protected String pseStatusC;
        @XmlElement(name = "pse__Approved__c")
        protected String pseApprovedC;
        @XmlElement(name = "pse__Include_In_Financials__c")
        protected String pseIncludeInFinancialsC;
        @XmlElement(name = "pse__Transaction_Category__c")
        protected String pseTransactionCategoryC;
        @XmlElement(name = "pse__Invoiced__c")
        protected String pseInvoicedC;
        @XmlElement(name = "pse__Billed__c")
        protected String pseBilledC;
        @XmlElement(name = "Estimate_Category__c")
        protected String estimateCategoryC;
        @XmlElement(name = "Time_Period__r")
        protected String timePeriodR;
        @XmlElement(name = "pse__Project__r")
        protected String pseProjectR;
        @XmlElement(name = "pse__Vendor_Account__r")
        protected String pseVendorAccountR;

        /**
         * Gets the value of the miscAdjustmentPSKeyC property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMiscAdjustmentPSKeyC() {
            return miscAdjustmentPSKeyC;
        }

        /**
         * Sets the value of the miscAdjustmentPSKeyC property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMiscAdjustmentPSKeyC(String value) {
            this.miscAdjustmentPSKeyC = value;
        }

        /**
         * Gets the value of the sourceTypeC property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSourceTypeC() {
            return sourceTypeC;
        }

        /**
         * Sets the value of the sourceTypeC property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSourceTypeC(String value) {
            this.sourceTypeC = value;
        }

        /**
         * Gets the value of the pseEffectiveDateC property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPseEffectiveDateC() {
            return pseEffectiveDateC;
        }

        /**
         * Sets the value of the pseEffectiveDateC property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPseEffectiveDateC(String value) {
            this.pseEffectiveDateC = value;
        }

        /**
         * Gets the value of the effectiveDateIntegrationC property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEffectiveDateIntegrationC() {
            return effectiveDateIntegrationC;
        }

        /**
         * Sets the value of the effectiveDateIntegrationC property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEffectiveDateIntegrationC(String value) {
            this.effectiveDateIntegrationC = value;
        }

        /**
         * Gets the value of the poNumberC property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPONumberC() {
            return poNumberC;
        }

        /**
         * Sets the value of the poNumberC property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPONumberC(String value) {
            this.poNumberC = value;
        }

        /**
         * Gets the value of the pseDescriptionC property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPseDescriptionC() {
            return pseDescriptionC;
        }

        /**
         * Sets the value of the pseDescriptionC property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPseDescriptionC(String value) {
            this.pseDescriptionC = value;
        }

        /**
         * Gets the value of the pseInvoiceNumberC property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPseInvoiceNumberC() {
            return pseInvoiceNumberC;
        }

        /**
         * Sets the value of the pseInvoiceNumberC property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPseInvoiceNumberC(String value) {
            this.pseInvoiceNumberC = value;
        }

        /**
         * Gets the value of the pseInvoiceDateC property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPseInvoiceDateC() {
            return pseInvoiceDateC;
        }

        /**
         * Sets the value of the pseInvoiceDateC property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPseInvoiceDateC(String value) {
            this.pseInvoiceDateC = value;
        }

        /**
         * Gets the value of the currencyIsoCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCurrencyIsoCode() {
            return currencyIsoCode;
        }

        /**
         * Sets the value of the currencyIsoCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCurrencyIsoCode(String value) {
            this.currencyIsoCode = value;
        }

        /**
         * Gets the value of the pseAmountC property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPseAmountC() {
            return pseAmountC;
        }

        /**
         * Sets the value of the pseAmountC property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPseAmountC(String value) {
            this.pseAmountC = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the pseStatusC property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPseStatusC() {
            return pseStatusC;
        }

        /**
         * Sets the value of the pseStatusC property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPseStatusC(String value) {
            this.pseStatusC = value;
        }

        /**
         * Gets the value of the pseApprovedC property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPseApprovedC() {
            return pseApprovedC;
        }

        /**
         * Sets the value of the pseApprovedC property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPseApprovedC(String value) {
            this.pseApprovedC = value;
        }

        /**
         * Gets the value of the pseIncludeInFinancialsC property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPseIncludeInFinancialsC() {
            return pseIncludeInFinancialsC;
        }

        /**
         * Sets the value of the pseIncludeInFinancialsC property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPseIncludeInFinancialsC(String value) {
            this.pseIncludeInFinancialsC = value;
        }

        /**
         * Gets the value of the pseTransactionCategoryC property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPseTransactionCategoryC() {
            return pseTransactionCategoryC;
        }

        /**
         * Sets the value of the pseTransactionCategoryC property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPseTransactionCategoryC(String value) {
            this.pseTransactionCategoryC = value;
        }

        /**
         * Gets the value of the pseInvoicedC property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPseInvoicedC() {
            return pseInvoicedC;
        }

        /**
         * Sets the value of the pseInvoicedC property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPseInvoicedC(String value) {
            this.pseInvoicedC = value;
        }

        /**
         * Gets the value of the pseBilledC property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPseBilledC() {
            return pseBilledC;
        }

        /**
         * Sets the value of the pseBilledC property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPseBilledC(String value) {
            this.pseBilledC = value;
        }

        /**
         * Gets the value of the estimateCategoryC property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEstimateCategoryC() {
            return estimateCategoryC;
        }

        /**
         * Sets the value of the estimateCategoryC property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEstimateCategoryC(String value) {
            this.estimateCategoryC = value;
        }

        /**
         * Gets the value of the timePeriodR property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTimePeriodR() {
            return timePeriodR;
        }

        /**
         * Sets the value of the timePeriodR property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTimePeriodR(String value) {
            this.timePeriodR = value;
        }

        /**
         * Gets the value of the pseProjectR property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPseProjectR() {
            return pseProjectR;
        }

        /**
         * Sets the value of the pseProjectR property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPseProjectR(String value) {
            this.pseProjectR = value;
        }

        /**
         * Gets the value of the pseVendorAccountR property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPseVendorAccountR() {
            return pseVendorAccountR;
        }

        /**
         * Sets the value of the pseVendorAccountR property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPseVendorAccountR(String value) {
            this.pseVendorAccountR = value;
        }

		@Override
		public String toString() {
			return "PseMiscellaneousAdjustmentC [miscAdjustmentPSKeyC="
					+ miscAdjustmentPSKeyC + ", sourceTypeC=" + sourceTypeC
					+ ", pseEffectiveDateC=" + pseEffectiveDateC
					+ ", effectiveDateIntegrationC="
					+ effectiveDateIntegrationC + ", poNumberC=" + poNumberC
					+ ", pseDescriptionC=" + pseDescriptionC
					+ ", pseInvoiceNumberC=" + pseInvoiceNumberC
					+ ", pseInvoiceDateC=" + pseInvoiceDateC
					+ ", currencyIsoCode=" + currencyIsoCode + ", pseAmountC="
					+ pseAmountC + ", name=" + name + ", pseStatusC="
					+ pseStatusC + ", pseApprovedC=" + pseApprovedC
					+ ", pseIncludeInFinancialsC=" + pseIncludeInFinancialsC
					+ ", pseTransactionCategoryC=" + pseTransactionCategoryC
					+ ", pseInvoicedC=" + pseInvoicedC + ", pseBilledC="
					+ pseBilledC + ", estimateCategoryC=" + estimateCategoryC
					+ ", timePeriodR=" + timePeriodR + ", pseProjectR="
					+ pseProjectR + ", pseVendorAccountR=" + pseVendorAccountR
					+ "]";
		}
        
    }
    
	@Override
	public String toString() {
		return "InputElement [pseMiscellaneousAdjustmentC="
				+ pseMiscellaneousAdjustmentC + "]";
	}
    
}
